###
#  █████╗ ███╗   ██╗ ██████╗ ███╗   ██╗██╗   ██╗███╗   ███╗ ██████╗ ██╗   ██╗███████╗
# ██╔══██╗████╗  ██║██╔═══██╗████╗  ██║╚██╗ ██╔╝████╗ ████║██╔═══██╗██║   ██║██╔════╝
# ███████║██╔██╗ ██║██║   ██║██╔██╗ ██║ ╚████╔╝ ██╔████╔██║██║   ██║██║   ██║███████╗
# ██╔══██║██║╚██╗██║██║   ██║██║╚██╗██║  ╚██╔╝  ██║╚██╔╝██║██║   ██║██║   ██║╚════██║
# ██║  ██║██║ ╚████║╚██████╔╝██║ ╚████║   ██║   ██║ ╚═╝ ██║╚██████╔╝╚██████╔╝███████║
# ╚═╝  ╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═══╝   ╚═╝   ╚═╝     ╚═╝ ╚═════╝  ╚═════╝ ╚══════╝

###
GET {{baseURL}}/api/GetCurrentTime

###
GET {{baseURL}}/api/GetNext

###
GET {{baseURL}}/api/GetAll

###
# ███████╗███████╗██████╗ ██╗███████╗███████╗
# ██╔════╝██╔════╝██╔══██╗██║██╔════╝██╔════╝
# ███████╗█████╗  ██████╔╝██║█████╗  ███████╗
# ╚════██║██╔══╝  ██╔══██╗██║██╔══╝  ╚════██║
# ███████║███████╗██║  ██║██║███████╗███████║
# ╚══════╝╚══════╝╚═╝  ╚═╝╚═╝╚══════╝╚══════╝

### Get the list of all series
GET {{baseURL}}/api/Series
x-functions-key: {{key}}


### Get the details of a specific series
GET {{baseURL}}/api/Series/1
x-functions-key: {{key}}

### Update the specified series
PUT {{baseURL}}/api/Series/1
x-functions-key: {{key}}
Content-Type: application/json
{
  "Name": "Sunday Morning Worship",
  "Day": 0,
  "Hours": 10,
  "Minutes": 30
}

###
#  ██████╗ █████╗ ███╗   ██╗ ██████╗███████╗██╗     ██╗      █████╗ ████████╗██╗ ██████╗ ███╗   ██╗███████╗
# ██╔════╝██╔══██╗████╗  ██║██╔════╝██╔════╝██║     ██║     ██╔══██╗╚══██╔══╝██║██╔═══██╗████╗  ██║██╔════╝
# ██║     ███████║██╔██╗ ██║██║     █████╗  ██║     ██║     ███████║   ██║   ██║██║   ██║██╔██╗ ██║███████╗
# ██║     ██╔══██║██║╚██╗██║██║     ██╔══╝  ██║     ██║     ██╔══██║   ██║   ██║██║   ██║██║╚██╗██║╚════██║
# ╚██████╗██║  ██║██║ ╚████║╚██████╗███████╗███████╗███████╗██║  ██║   ██║   ██║╚██████╔╝██║ ╚████║███████║
#  ╚═════╝╚═╝  ╚═╝╚═╝  ╚═══╝ ╚═════╝╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝   ╚═╝   ╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝

###
# ███████╗██████╗ ███████╗ ██████╗██╗ █████╗ ██╗     ███████╗
# ██╔════╝██╔══██╗██╔════╝██╔════╝██║██╔══██╗██║     ██╔════╝
# ███████╗██████╔╝█████╗  ██║     ██║███████║██║     ███████╗
# ╚════██║██╔═══╝ ██╔══╝  ██║     ██║██╔══██║██║     ╚════██║
# ███████║██║     ███████╗╚██████╗██║██║  ██║███████╗███████║
# ╚══════╝╚═╝     ╚══════╝ ╚═════╝╚═╝╚═╝  ╚═╝╚══════╝╚══════╝

### Get the list of all specials
GET {{baseURL}}/api/Specials

### Creates a new special
POST {{baseURL}}/api/Specials
Content-Type: application/json
{
  "DateTime": "2026-04-15T08:00:00Z",
  "Name": "Test special 8:00 AM"
}

### Updates the specified special
PUT {{baseURL}}/api/Specials/3
Content-Type: application/json
{
  "DateTime": "2026-04-15T09:00:00Z",
  "Name": "Test special 9:00 AM"
}

### Deletes the specified special
DELETE {{baseURL}}/api/Specials/3
